version: '3.4'

services:
  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus/:/etc/prometheus/
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:9090/-/healthy && exit 0
      interval: 10s
      timeout: 30s
      retries: 3
      start_period: 10s
  grafana:
    image: grafana/grafana-enterprise:10.0.0
    ports:
      - 3000:3000
    volumes:
      - grafana-storage:/var/lib/grafana
    healthcheck:
      test: curl http://localhost:3000/api/health && exit 0
      interval: 10s
      timeout: 30s
      retries: 3
      start_period: 10s
  gomongodb:
    image: gomongodb
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080
    env_file:
      - .env
    depends_on:
      prometheus:
        condition: service_healthy
      grafana:
        condition: service_healthy
volumes:
  grafana-storage: