FROM golang:1.20.4-bullseye

WORKDIR /bin

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o /bin/go_rest_app

ARG SERVING_PORT=8080

ENV C1_DB_USERNAME=C1_DB_USERNAME
ENV C1_DB_PASSWORD=C1_DB_PASSWORD
ENV C1_DB_CLUSTER=C1_DB_CLUSTER
ENV C1_DB_AIRBNB=C1_DB_AIRBNB
ENV C1_DB_AIRBNB_COLLEC_LISTINGS=C1_DB_AIRBNB_COLLEC_LISTINGS

ENV SERVING_PORT=${SERVING_PORT}

EXPOSE $SERVING_PORT

CMD [ "go_rest_app" ]
