global:
  scrape_interval: 15s
  external_labels:
    monitor: 'codelab-monitor'
scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'mongo-crud'
    scrape_interval: 5s
    metrics_path: /metrics
    static_configs:
      - targets:
          - "gomongodb:8080"