global:
  scrape_interval: 15s
  external_labels:
    monitor: "codelab-monitor"
rule_files:
  - "prometheus.rules.yml"
scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 5s
    static_configs:
      - targets: ["localhost:9090"]
        labels:
          group: "production"
  - job_name: "mongo-crud"
    scrape_interval: 5s
    metrics_path: /metrics
    static_configs:
      - targets: ["gomongodb:8080"]
        labels:
          group: "production"

